### ISSUE TITLE
"Can't load timezones"...?

### ISSUE THREAD

**Issue by d33tah** [SergeyMosin/Appointments#243]
I'm getting the following error on NextCloud 21.0.4 (calendar app upgraded to the latest current version):

```
Can't get timezone script.js:2:1528496
    n https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    u https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    _invoke https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    w https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    Li https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    s https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    (Async: promise callback)
    Li https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    i https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    (Async: promise callback)
    Li https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    i https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    (Async: promise callback)
    Li https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    i https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    Pi https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    Pi https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    start https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    mounted https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    Ht https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    se https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    insert https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    k https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    vr https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    _update https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    a https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    get https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    run https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    ve https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    rn https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    Xt https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    (Async: promise callback)
    qt https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    rn https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    update https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    update https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    notify https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    set https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    set https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    toggleSlideBar https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    openViaPicker https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
Error: Can't get_tz
    n https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    u https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    _invoke https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    w https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    Li https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    i https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    promise callback*Li https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    i https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    promise callback*Li https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    i https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    Pi https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    Pi https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    getTimeZone https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    n https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    u https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    _invoke https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    w https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    Li https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    i https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    promise callback*Li https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    i https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    promise callback*Li https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    i https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    Pi https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    Pi https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    start https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    mounted https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    Ht https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    se https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    insert https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    k https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    vr https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    _update https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    a https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    get https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    run https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    ve https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    rn https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    Xt https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    promise callback*qt https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    rn https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    update https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    update https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    notify https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    set https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    set https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    toggleSlideBar https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
    openViaPicker https://nextcloud.hs-ldz.pl/custom_apps/appointments/js/script.js?v=b475c477-0:2
```

Tested under Firefox 93. Here's the settings dump:

```
Nextcloud Version: 21.0.4
Appointments Version: 1.10.2
Key: No

org_info: array (
  'organization' => 'asd',
  'email' => 'qwe@qwe.pl',
  'address' => 'zxc',
  'phone' => '123',
)

email_options: array (
  'icsFile' => false,
  'skipEVS' => false,
  'attMod' => true,
  'attDel' => true,
  'meReq' => false,
  'meConfirm' => false,
  'meCancel' => false,
  'vldNote' => '',
  'cnfNote' => '',
)

calendar_settings: array (
  'mainCalId' => '-1',
  'destCalId' => '-1',
  'nrSrcCalId' => '-1',
  'nrDstCalId' => '-1',
  'nrPushRec' => true,
  'nrRequireCat' => false,
  'nrAutoFix' => false,
  'tmmDstCalId' => '7',
  'tmmMoreCals' => 
  array (
  ),
  'prepTime' => '0',
  'whenCanceled' => 'mark',
  'allDayBlock' => true,
  'tsMode' => '2',
)

page_options: array (
  'formTitle' => '',
  'nbrWeeks' => '1',
  'showEmpty' => true,
  'startFNED' => false,
  'showWeekends' => false,
  'time2Cols' => false,
  'endTime' => false,
  'hidePhone' => false,
  'showTZ' => false,
  'gdpr' => '',
  'pageTitle' => '',
  'pageSubTitle' => '',
  'metaNoIndex' => false,
  'pageStyle' => '',
)

more_pages: array (
  'mainCalId' => '-1',
  'destCalId' => '-1',
  'nrSrcCalId' => '-1',
  'nrDstCalId' => '-1',
  'tmmDstCalId' => '-1',
  'tmmMoreCals' => 
  array (
  ),
  'tsMode' => '2',
  'organization' => '',
  'email' => '',
  'address' => '',
  'phone' => '',
  'formTitle' => '',
)

pages: array (
  'p0' => 
  array (
    'enabled' => 0,
    'label' => 'd33tah',
  ),
)

dir_info: array (
)

appt_talk: array (
  'enabled' => false,
  'delete' => false,
  'emailText' => '',
  'lobby' => false,
  'password' => false,
  'nameFormat' => 0,
  'formFieldEnable' => false,
  'formLabel' => '',
  'formPlaceholder' => '',
  'formTxtReal' => '',
  'formTxtVirtual' => '',
  'formTxtTypeChange' => '',
  'formDefLabel' => 'Rodzaj spotkania',
  'formDefPlaceholder' => 'Wybierz rodzaj spotkania',
  'formDefReal' => 'Spotkanie osobiste',
  'formDefVirtual' => 'Online (audio/wideo)',
)

fi_json: array (
)

fi_html: array (
  0 => '',
)

useDefaultEmail: NULL

emailFixOpt: NULL

template_info: array (
  'tzName' => '',
  'tzData' => '',
)

template_data: array (
)
```

**Comment by support-tt** [comment]
Hello I have the same problem also with timezone CEST.
Nextcloud Version Nextcloud 22.1.1 (Docker nextcloud:fpm-alpine image)
This is the log (which was produced from browser debug during try so maybe there are also messages that doesnt have anything to to with the appaintment app)
`
script?v=16:115 Uncaught TypeError: Cannot read properties of null (reading 'parentNode')
    at script?v=16:115
    at script?v=16:332
session-heartbeat.js:101 session heartbeat polling started
form.js?v=6ddc330b-57:1 data-state:  4
globals.js:62 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
ue @ globals.js:62
script?v=16:69 Uncaught TypeError: Cannot read properties of null (reading 'addEventListener')
    at HTMLBodyElement.<anonymous> (script?v=16:69)
    at _ (sideMenu.js?v=6ddc330b-57:24)
script.js?v=6ddc330b-57:2 Can't get timezone
(anonymous) @ script.js?v=6ddc330b-57:2
script.js?v=6ddc330b-57:2 Error: Can't get_tz
    at script.js?v=6ddc330b-57:2
    at u (script.js?v=6ddc330b-57:2)
    at Generator._invoke (script.js?v=6ddc330b-57:2)
    at Generator.next (script.js?v=6ddc330b-57:2)
    at Li (script.js?v=6ddc330b-57:2)
    at i (script.js?v=6ddc330b-57:2)
util.js:135 OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment
relativeModifiedDate @ util.js:135

`

**Comment by SergeyMosin** [comment]
v1.11.2 has a `Timezone` info in  "debugging/settings dump" section which looks something like this:
```
Nextcloud Version: 22.2.3
Appointments Version: 1.11.2
Timezone: America/New_York
Key: Yes

org_info: array (
  'organization' => 'Good Org',
...
```
Can you please tell me what does it say on your system, so I can try to reproduce this.

Thanks

**Comment by support-tt** [comment]
I upgraded the Version today but same issue:
```
Nextcloud Version: 22.2.2
Appointments Version: 1.11.2
Timezone: UTC
Key: No

org_info: array (
  'organization' => 'Test',
  'email' => 'test@testdomain.de',
  'address' => 'Frankfurt',
  'phone' => '123456',
)

email_options: array (
  'icsFile' => false,
  'skipEVS' => false,
  'attMod' => true,
  'attDel' => true,
  'meReq' => false,
  'meConfirm' => false,
  'meCancel' => false,
  'vldNote' => '',
  'cnfNote' => '',
)

calendar_settings: array (
  'mainCalId' => '-1',
  'destCalId' => '-1',
  'nrSrcCalId' => '-1',
  'nrDstCalId' => '-1',
  'nrPushRec' => true,
  'nrRequireCat' => false,
  'nrAutoFix' => false,
  'tmmDstCalId' => '-1',
  'tmmMoreCals' => 
  array (
  ),
  'prepTime' => '0',
  'whenCanceled' => 'mark',
  'allDayBlock' => false,
  'tsMode' => '2',
)

page_options: array (
  'formTitle' => '',
  'nbrWeeks' => '1',
  'showEmpty' => true,
  'startFNED' => false,
  'showWeekends' => false,
  'time2Cols' => false,
  'endTime' => false,
  'hidePhone' => false,
  'showTZ' => false,
  'gdpr' => '',
  'pageTitle' => '',
  'pageSubTitle' => '',
  'metaNoIndex' => false,
  'pageStyle' => '',
)

more_pages: array (
  'mainCalId' => '-1',
  'destCalId' => '-1',
  'nrSrcCalId' => '-1',
  'nrDstCalId' => '-1',
  'tmmDstCalId' => '-1',
  'tmmMoreCals' => 
  array (
  ),
  'tsMode' => '2',
  'organization' => '',
  'email' => '',
  'address' => '',
  'phone' => '',
  'formTitle' => '',
)

pages: array (
  'p0' => 
  array (
    'enabled' => 0,
    'label' => '',
  ),
)

dir_info: array (
)

reminders: array (
  'data' => 
  array (
    0 => 
    array (
      'seconds' => '0',
      'actions' => true,
    ),
    1 => 
    array (
      'seconds' => '0',
      'actions' => true,
    ),
    2 => 
    array (
      'seconds' => '0',
      'actions' => true,
    ),
  ),
  'friday' => false,
  'moreText' => '',
)

appt_talk: array (
  'enabled' => false,
  'delete' => false,
  'emailText' => '',
  'lobby' => false,
  'password' => false,
  'nameFormat' => 0,
  'formFieldEnable' => false,
  'formLabel' => '',
  'formPlaceholder' => '',
  'formTxtReal' => '',
  'formTxtVirtual' => '',
  'formTxtTypeChange' => '',
  'formDefLabel' => 'Besprechungstyp',
  'formDefPlaceholder' => 'Besprechungstyp auswählen',
  'formDefReal' => 'Persönliche Besprechung',
  'formDefVirtual' => 'Online (Audio/Video)',
)

fi_json: array (
)

fi_html: array (
  0 => '',
)

useDefaultEmail: NULL

emailFixOpt: NULL

template_info: array (
  'tzName' => '',
  'tzData' => '',
)

template_data: array (
)

```
![image](https://user-images.githubusercontent.com/61587422/141987637-71239ffe-d1c8-4df0-bda2-74ede10cccc8.png)

**Comment by SergeyMosin** [comment]
@support-tt Thank you, I found the error in JS, it is related to the handling of "UTC". But a you should have had "Europe/Berlin" instead of "UTC", I'll try to get to the bottom of this. Thanks again for the info.

**Comment by SergeyMosin** [comment]
Should be fixed in v1.11.3

**Comment by support-tt** [comment]
I installed the Update and deleted my cookies now I got a new issue:
![image](https://user-images.githubusercontent.com/61587422/143920474-008d2fff-54db-4002-8f91-d956e40f4cc7.png)

This is with every calender I got. 

Maybe I do something wrong..

This is the Debug:

> Nextcloud Version: 22.2.2
> Appointments Version: 1.11.3
> Time zone: UTC (calendar: automatic, core: N/A)
> Key: No
> 
> org_info: array (
>   'organization' => 'Test',
>   'email' => '[email protected]',
>   'address' => 'Frankfurt',
>   'phone' => '123456',
> )
> 
> email_options: array (
>   'icsFile' => false,
>   'skipEVS' => false,
>   'attMod' => true,
>   'attDel' => true,
>   'meReq' => false,
>   'meConfirm' => false,
>   'meCancel' => false,
>   'vldNote' => '',
>   'cnfNote' => '',
> )
> 
> calendar_settings: array (
>   'mainCalId' => '-1',
>   'destCalId' => '41',
>   'nrSrcCalId' => '-1',
>   'nrDstCalId' => '-1',
>   'nrPushRec' => true,
>   'nrRequireCat' => false,
>   'nrAutoFix' => true,
>   'tmmDstCalId' => '39',
>   'tmmMoreCals' => 
>   array (
>   ),
>   'prepTime' => '0',
>   'whenCanceled' => 'mark',
>   'allDayBlock' => false,
>   'tsMode' => '2',
> )
> 
> page_options: array (
>   'formTitle' => '',
>   'nbrWeeks' => '1',
>   'showEmpty' => true,
>   'startFNED' => false,
>   'showWeekends' => false,
>   'time2Cols' => false,
>   'endTime' => false,
>   'hidePhone' => false,
>   'showTZ' => false,
>   'gdpr' => '',
>   'pageTitle' => '',
>   'pageSubTitle' => '',
>   'metaNoIndex' => false,
>   'pageStyle' => '',
> )
> 
> more_pages: NULL
> 
> pages: array (
>   'p0' => 
>   array (
>     'enabled' => 0,
>     'label' => '',
>   ),
> )
> 
> dir_info: array (
> )
> 
> reminders: array (
>   'data' => 
>   array (
>     0 => 
>     array (
>       'seconds' => '0',
>       'actions' => true,
>     ),
>     1 => 
>     array (
>       'seconds' => '0',
>       'actions' => true,
>     ),
>     2 => 
>     array (
>       'seconds' => '0',
>       'actions' => true,
>     ),
>   ),
>   'friday' => false,
>   'moreText' => '',
> )
> 
> appt_talk: array (
>   'enabled' => false,
>   'delete' => false,
>   'emailText' => '',
>   'lobby' => false,
>   'password' => false,
>   'nameFormat' => 0,
>   'formFieldEnable' => false,
>   'formLabel' => '',
>   'formPlaceholder' => '',
>   'formTxtReal' => '',
>   'formTxtVirtual' => '',
>   'formTxtTypeChange' => '',
>   'formDefLabel' => 'Besprechungstyp',
>   'formDefPlaceholder' => 'Besprechungstyp auswählen',
>   'formDefReal' => 'Persönliche Besprechung',
>   'formDefVirtual' => 'Online (Audio/Video)',
> )
> 
> fi_json: array (
> )
> 
> fi_html: array (
>   0 => '',
> )
> 
> useDefaultEmail: NULL
> 
> emailFixOpt: NULL
> 
> template_info: array (
>   'tzName' => '',
>   'tzData' => '',
> )
> 
> template_data: array (
> )

**Comment by SergeyMosin** [comment]
@support-tt Thank you for the report. That was an error on my side. I just pushed a hotfix v1.11.4 which will fix the `Time zone data is empty` an should be available NC App Store in 20-30 minutes.

Also auto detection might not work with `Personal` calendar, can you create a new calendar which will have time zone preset by NC and this data will then be used by appointments.

**Comment by support-tt** [comment]
@SergeyMosin: Thank you it's working now with a new calender.
With the "old" ones (that are not the personal ones) I still get "fallback to timezone Europe/London".(maybe something in the nextcloud-database because this calenders are older?)

But with newly created calender it's working fine with Europe/Berlin. For me thats totally fine.

**Comment by xeruf** [comment]
I still get "fallback to timezone Europe/London" for appointments my personal calendar even though I am in CEST and calendar shows Europe/Berlin as above, with everything having been setup in the last weeks.

**Comment by xeruf** [comment]
See https://github.com/SergeyMosin/Appointments/issues/274
