### ISSUE TITLE
No mail send to inviter

### ISSUE THREAD

**Issue by tomcatcw1980** [SergeyMosin/Appointments#383]
Hello together,

first of all thank you very much for this great app. 

The app works wonderfully, except for one small problem: When a user books an appointment, the user receives an appointment confirmation email. However, as the inviter, I do not receive an email about the booked or cancelled appointment. 

The email settings are set correctly and all other email notifications work as well.

Do you have any idea what this could be?

Thank you very much in advance.

Regards
Christian

**Comment by tomcatcw1980** [comment]
Hi Sergey,

exactly, the settings are similar to yours. I just tested it and booked for test purposes. The nextcloud.log shows the folling error:

"Bad oma count"

[appointments] Fehler: Bad oma count

GET /index.php/apps/appointments/pub/Ya3oKOAZ28JFNqA38Cc7/cncf?d=2eTkpY6yGSFhHBaLnunDQ%2F7LTKOHFygA2xyJPJf9AP2GUwBljlniDyQxGENSoHKk3k2jgKBP9ufkYvH1qkWfL033RkdXiljK97XjP85l3hbU%3D
from _"hidden"_ at 2022-11-26T22:22:49+01:00

Does this help you to find out more?

**Comment by SergeyMosin** [comment]
This is very strange, "oma count" is basically line count in an appointment's description (see below)

It should be between 1 and 9 lines, what is the description for the appointment with failed email ?

Relevant code is here, btw:
https://github.com/SergeyMosin/Appointments/blob/807433cb6fdd45bc7384d76ce3da2193534fa039/lib/Backend/DavListener.php#L913-L920



![image](https://user-images.githubusercontent.com/10747559/204110433-f8582e2f-0c4d-4301-862e-28aaa227e159.png)

**Comment by mophilly** [comment]
Just a guess... it appears the case of the result of $omc = count($oma) being zero or null would also raise the error. Is text in the entry field required?

**Comment by SergeyMosin** [comment]
> Is text in the entry field required?

This text is being sent to organizer, if there is no text then organizer email will not be sent.

**Comment by mophilly** [comment]
> This text is being sent to organizer, if there is no text then organizer email will not be sent.

Ah. So perhaps another case in the if/else clause for a user message to that effect. and/or the option to sent to inviter even if empty. 

BTW, thanks for building this. It appears to be a great contribution.

**Comment by iamkhalidbashir** [comment]
I too am getting this issue
No emails are being sent to me
<img width="214" alt="appointment" src="https://user-images.githubusercontent.com/27646811/204729525-2f9f61b0-07a6-4e80-a694-a07f6c53eaac.PNG">

**Comment by SergeyMosin** [comment]
@iamkhalidbashir If possible can you check NC logs for any error messages from Appointments App

I can not reproduce this.

**Comment by tomcatcw1980** [comment]
Hi there,

I could reproduce the failure. I deleted my additional confirmation text and added only one line (one word). With one word in one line the inviter received a confirmation e-mail. Then I add I few more lines and voila the inviter does not get an mail.

Similar to iamkhalidbashir who has more then one line.

Maybe this the right direction. Please try again.

Thank you.

**Comment by SergeyMosin** [comment]
Ah. I see now, the `Additional ICS file description` is also added to appointment `DESCRIPTION` which in some cases overflows the limit of 8 lines of text for organizer emails.
Should be fixed in the next release.

**Comment by iamkhalidbashir** [comment]
I can confirm after changing the additional confirmation text to one-liner
I got the confirmation email.

**Comment by SergeyMosin** [comment]
fixed in v1.14.5

**Comment by tomcatcw1980** [comment]
Hey Sergey,

I just updated to 1.14.6, but the error still persists. No mails received as inviter. Even the "oma error" still exits in the logs.

My text consists of 23 words and goes over 6 lines

Greetings.

**Comment by tomcatcw1980** [comment]
Hey Sergey, I just adjusted the format and deleted some paragraphs. Now I receive the confirmation email.

Thank you.

**Comment by Kalistia** [comment]
Hello everyone!
I'm using 1.15.3 and as ppl said before, I can't manage to make the app send a mail to me when an attendee books an appointment. The mail is sent to them but not me (the adress used to send email on my nextcloud).

all my "additional CONFIRMATION email text" and "additional ICS file description" are empty and I even tried to unckeck the "attach .ics file" but without luck...

What am I doing wrongly?

Thank you!

**Comment by SergeyMosin** [comment]
@Kalistia 
Can you send me (sergey [at] srgdev.com) your settings dump `Appointments App > Settings > Advanced settings > Debugging > Settings dump` so I can try to replicate this in my development environment.
