### ISSUE TITLE
Simply does not work

### ISSUE THREAD

**Issue by tekntrash** [SergeyMosin/Appointments#392]
I created and configured everything and whenever I try to create an appointment I always get 

An error has occurred
Please try again later

Thank you

You can try yourself and see 
https://alcosta.eu/index.php/apps/appointments/pub/fTEeJfgltuEwWIJ96JrF5_k%3D/form

**Comment by SergeyMosin** [comment]
I got to the email validation step, but the email never arrived. Is there anything in NC error logs ? 

![image](https://user-images.githubusercontent.com/10747559/211573496-9d8243f0-f40e-4c45-a4e3-7857756f6841.png)

**Comment by tekntrash** [comment]
I am getting emails when I try it

What I noticed is that according to what you put in the fields such as name etc it will yield an error or not: I believe they must be lacking some checking so it ends up trying to insert grabage in the database and thus it crashes

Try putting letters in the phone field, improperly formatted emails, long texts, etc and see

**Comment by tekntrash** [comment]
Also, it is worth noting that if the person is using caldav synchronizer to sync with outlook and it has set to "outlook->server replicate" the next time it syncs it will automatically cancel the meeting. That may happen with similar softwares too, and it may be worth putting it in the manual. Hope that was useful :)

**Comment by SergeyMosin** [comment]
Bug confirmed. Translation module is not available (regression from public page optimization) which throws an error for example here: https://github.com/SergeyMosin/Appointments/blob/master/src/form.js#L105

@tekntrash thanks for the report

P.S. Probably a better error message is needed when form validation fails server-side
https://github.com/SergeyMosin/Appointments/blob/master/templates/public/formerr.php#L19-L21

**Comment by SergeyMosin** [comment]
> I am getting emails when I try it

Just FYI, I checked my mail server logs and it looks there is a rDNS lookup issue with mail.alcosta.eu/89.242.2.251 

```
Jan 10 09:46:14 srgdev postfix/postscreen[50320]: CONNECT from [89.242.2.251]:53260 to [66.228.40.106]:25
Jan 10 09:46:15 srgdev postfix/smtpd[50321]: warning: hostname mail.tekntrash.com does not resolve to address 89.242.2.251
Jan 10 09:46:15 srgdev postfix/smtpd[50321]: connect from unknown[89.242.2.251]
Jan 10 09:46:15 srgdev postfix/smtpd[50321]: Anonymous TLS connection established from unknown[89.242.2.251]: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature RSA-PSS (4096 bits) server-digest SHA256
Jan 10 09:46:15 srgdev postfix/smtpd[50322]: NOQUEUE: reject: RCPT from unknown[89.242.2.251]: 450 4.7.25 Client host rejected: cannot find your hostname, [89.242.2.251]; from=<appo***reducted***@alcosta.eu> to=<ser***reducted***@srgdev.com> proto=ESMTP helo=<mail.alcosta.eu>
Jan 10 09:46:15 srgdev postfix/smtpd[50322]: disconnect from unknown[89.242.2.251] ehlo=2 starttls=1 mail=1 rcpt=0/1 data=0/1 rset=1 quit=1 commands=6/8
```

**Comment by tekntrash** [comment]
Yes, its reverse DNS and SPF are unconfigured and have no time to do that :)

Glad to help on the bug, let me know when you have an update ok? Thanks!

**Comment by SergeyMosin** [comment]
fixed in v1.14.9

**Comment by tekntrash** [comment]
Great, still not showing on the nextcloud app portal though, guess I am too eager :)
