### ISSUE TITLE
Request: Timezone read from Browser confuses visitors

### ISSUE THREAD

**Issue by EkkiBrue** [SergeyMosin/Appointments#451]
Hi Sergey.

Thank you for your wonderfull appointments app. It´s a blast and makes life sooo much easier ;) I just sent you a symbolic obulus and I really hope it helps continuing the work you do! 

Nevertheless I´d like to ask for a little feature request as I´m having a little problem with certain "safe" browsers. Modern "safe" browsers (such as "MULL" on Android and "TOR Browser") seem to  prevent fingerprinting. One mechanism of preventing this is to answer a request for the timezone in an "obfuscated" manner. 

Appointments seems to read the timezone from the browser. Means: Appointments shows "wrong" Appointment time or date if the visitor is using this browsers and is not aware of the timezone he´s requesting the appointment. We had the first 2 cases here with people using this.

Yes, I am showing the timezone to the visitor (as made available in the extended settings) - but I guess nobody will get it.

Could you please make it possible that we set a timezone on our own (probably the one set in nextcloud for the source calendar) and that the timezone is not relying on the output of the browser API ?

Thank you!

**Comment by SergeyMosin** [comment]
At the moment most of the work is going into version 2 therefore I can not do a full implementation via the settings dialog for v1. However, a workaround is possible in v1.5.14, timezone can be controlled via URL query parameter...

For example to force `Tokyo` timezone, you would add `?tz=Asia/Tokyo` to the end of your appointments page URL: 

Example: `https://your.domain.com/index.php/apps/appointments/pub/SoMeToKeN/form` -> `https://your.domain.com/index.php/apps/appointments/pub/SoMeToKeN/form?tz=Asia/Tokyo`

The list of valid time zones can be found here: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

**Comment by EkkiBrue** [comment]
Wow. That was fast. Thank you very much! It works like a charm now! Keep up the brillant work and thanks again for the barrier free support you provide here. If there is anything I can help you with (like betatesting 2.0 or whatever) just let me know.

**Comment by Raudius** [comment]
Maybe simpler solution would be to use the locale set in the Nextcloud user profile? This would save having to develop it in the settings of this app, and would be better for UX since the timezone only has to be set once.

**Comment by Jolopu** [comment]
I also would like to help. Can do beta testing and translation. :-)

**Comment by SergeyMosin** [comment]
fixed via 356d454435f6416d9dbe1bdf3e80b4beb533ce17 in v2.2.0

**Comment by EkkiBrue** [comment]
Hi Sergey.

I´m still having issues with certain browsers reading the timezone right from nextcloud. It seemed you fixed it in 2.20 but e.b. Mull on Android (Firefox Fork available on FDroid ) still fails to set the timezone correctly. It always defaults back to "Greenwich-Time".

<img width="877" height="1620" alt="Image" src="https://github.com/user-attachments/assets/9cb6d7bb-4c44-4dcd-89e5-1281680a5a9d" />

It seems that passing the URL query parameter is not working anymore or has been turned off in apointments. 

This is the url I pass over inside an IFRAME.

https://xxxxxx.de/index.php/apps/appointments/embed/aZ5r5z5vbVwv8DGY/form?tz=Europe/Berlin

In the upper sample I pass the timezone via query and it is ignored in mull.

So my question is: Is it possible to bring the feature back ? Or is it still there and mull is favoring a wrong read Timezone instead of the query ?
