### ISSUE TITLE
Bug : Simple Time Slot Mode  - Already reserved date not removed from list of availability

### ISSUE THREAD

**Issue by acazenave** [SergeyMosin/Appointments#569]
Appointments version used : 2.3.4
Nextcloud version used : 28.0.11

For a page with simple time slot mode (for a weekly template it works well), when someone reserve a slot, then it is still shown as available in the list. 
But when someone else try to reserve this slot again, he get a 500 error. 
![image](https://github.com/user-attachments/assets/a604a2e2-4193-4b45-bc88-f5a789f78d66)

Logs : 
```
"message":"Lock uid already exists","userAgent"
"message":"Select different time"
"message":"setAttendee error status: 1"
```

I tried same config on an other Nextcloud with an older Appointments version 2.1.12 and I don't have this issue.

Expected behavior : 
When a slot is reserved it should be removed from available list.

**Comment by SergeyMosin** [comment]
Bug confirmed. Fix will be available ASAP.

**Comment by SergeyMosin** [comment]
Fixed in v2.3.5

**Comment by ben-no** [comment]
Unfortunately, the problem persists with the external Time Slot Mode.

**Comment by SergeyMosin** [comment]
@ben-no Can you send me ( sergey [at] srgdev.com ) the settings dump (`Settings > Advanced > Debugging > Settings Dump`) and the  event(`.ics`) that is supposed to block.

**Comment by SergeyMosin** [comment]
no activity - closing
